# Generated by Django 3.1.2 on 2020-10-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('team_1', models.CharField(max_length=100, verbose_name='Team 1')),
                ('team_2', models.CharField(max_length=100, verbose_name='Team 2')),
            ],
            options={
                'verbose_name': 'Season Calendar',
                'verbose_name_plural': 'Season Calendar',
                'unique_together': {('date', 'team_1', 'team_2')},
            },
        ),
    ]
